version: '3.8'

services:
  hardhat:
    build:
      context: .
      args:
        BUILD_TARGET: hardhat
    container_name: defi-hardhat
    ports:
      - "8545:8545"
    volumes:
      - ./hardhat:/app/hardhat
      - hardhat_node_modules:/app/hardhat/node_modules
    working_dir: /app/hardhat
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      - WALLET_ADDRESS=${WALLET_ADDRESS:-0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266}
    command: >
      bash -c "npm install &&
               npx hardhat clean &&
               npx hardhat compile &&
               npx hardhat node &
               sleep 20 &&
               envsubst < scripts/transferDF.js.template > scripts/transferDF.js &&
               envsubst < scripts/transferTokenForTesting.js.template > scripts/transferTokenForTesting.js &&
               npx hardhat run scripts/deploy_multiple_pools.js --network localhost &&
               npx hardhat run scripts/transferTokenForTesting.js --network localhost &&
               npx hardhat run scripts/transferDF.js --network localhost &&
               npx hardhat run scripts/add-liquidity.js --network localhost &&
               tail -f /dev/null"

  frontend:
    build:
      context: .
      args:
        BUILD_TARGET: frontend
    container_name: defi-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    working_dir: /app/frontend
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_51RD870IBisDm0c0SWt45p3mjynjmaccpQjXQi0xvqhQnJpDKMCUzdGV1QLszyp9aOZnjc6yuA83SD5pYYx2impiE00RBv5iPzl}
      - PRIVATE_KEY=${PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      - HARDHAT_URL=http://hardhat:8545
    command: bash -c "npm install && npm run dev"
    depends_on:
      - hardhat

volumes:
  hardhat_node_modules:
  frontend_node_modules: 