// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

"use client";
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "@/theme";
import { WalletProvider } from "@/context/WalletContext";
import BackgroundAnimation from "@/components/BackgroundAnimation";
import Header from "@/components/Header";
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<WalletProvider>
					<ThemeProvider theme={theme}>
						<CssBaseline />
						<BackgroundAnimation />
						<Header />
						{children}
					</ThemeProvider>
				</WalletProvider>
			</body>
		</html>
	);
}
