export const rawProducts = [
    {
      id: 1,
      name: "Vintage Camera",
      image: "https://picsum.photos/id/26/250",
      price: "200",
      token: "ALPHA",
      condition: "Lightly Used",
      description: "Classic 35mm film camera, great for collectors. Fully functional and comes with strap and case.",
      sellerWallet: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e",
      tokenType: "ALPHA",
      tokenContract: "0xTokenContractAddress",
      shipping: "Free shipping worldwide",
      shippingTime: "3-5 business days",
    },
    {
      id: 2,
      name: "Gaming Headset",
      image: "https://picsum.photos/id/91/250",
      price: "1000",
      token: "BETA",
      condition: "Brand New",
      description: "High-quality surround sound headset, perfect for immersive gaming.",
      sellerWallet: "0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B",
      tokenType: "BETA",
      tokenContract: "0xTokenContractAddress",
      shipping: "Free shipping worldwide",
      shippingTime: "5-7 business days",
    },
    {
      id: 3,
      name: "Mechanical Keyboard",
      image: "https://picsum.photos/id/119/250",
      price: "150",
      token: "CHARLIE",
      condition: "Used",
      description: "RGB backlit keyboard with blue switches, used for a few months.",
      sellerWallet: "0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0",
      tokenType: "CHARLIE",
      tokenContract: "0xTokenContractAddress",
      shipping: "Free shipping worldwide",
      shippingTime: "3-5 business days",
    },
    {
      id: 4,
      name: "Used Smartphone",
      image: "https://picsum.photos/250",
      price: "600",
      token: "DELTA",
      condition: "Heavily Used",
      description: "Older model smartphone, still functional. Some screen scratches.",
      sellerWallet: "0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B",
      tokenType: "DELTA",
      tokenContract: "0xTokenContractAddress",
      shipping: "Free shipping worldwide",
      shippingTime: "7-10 business days",
    }
  ];
  